name: CI

on: push

jobs:
  ui-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: install dependencies
      run: yarn install
    - name: run tests
      run: yarn test
